name: Preview build iOS

env:
  BUILD: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
      
jobs:
  test_lint_and_build:
      runs-on: macos-latest
      
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '20'
        
        - name: Install dependencies
          run: npm ci

        - name: Run ESLint
          run: npm run lint

        - name: Run Prettier
          run: npm run format
        
        - name: Run Jest tests
          run: npm run test

        - name: Setup EAS
          uses: expo/expo-github-action@v8
          with:
            eas-version: latest
            token: ${{ secrets.EXPO_TOKEN }}
        
        - name: Create preview build for iOS
          if: ${{ env.BUILD == 'true' }}
          run: eas build --platform ios --non-interactive --profile preview-simulator